version: '3.8'

services:
  db2_federated:
    image: ibmcom/db2:11.5.8.0
    container_name: db2_federated
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=db2inst1
      - DBNAME=BASETASD
      - BLU=false
      - ENABLE_ORACLE_COMPATIBILITY=true
    ports:
      - "50000:50000"
    volumes:
      - db2_federated_data:/database
      - ./scripts:/scripts:ro
      - ./data:/var/db2/files:rw

  db2_remote:
    image: ibmcom/db2:11.5.8.0
    container_name: db2_remote
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=db2inst1
      - DBNAME=SAMPLE
      - BLU=false
      - SAMPLEDATABASE=true
    ports:
      - "50001:50000"
    volumes:
      - db2_remote_data:/database
      - ./scripts:/scripts:ro
      - ./data:/var/db2/files:rw

volumes:
  db2_federated_data:
  db2_remote_data:
