connect to BASETASD;
DROP NICKNAME db2Ldept;
DROP NICKNAME db2Lemp;
DROP NICKNAME db2Lproj;
DROP USER MAPPING FOR DB2INST1 SERVER DB2SERVERLOCAL;
DROP SERVER DB2SERVERLOCAL;
DROP WRAPPER DRDA;
terminate;
