-- fix_federation.sql

CONNECT TO BASETASD;

-- Limpieza preventiva
-- Ignoramos errores si no existen
DROP NICKNAME db2Ldept;
DROP NICKNAME db2Lemp;
DROP NICKNAME db2Lproj;

DROP USER MAPPING FOR DB2INST1 SERVER DB2SERVERLOCAL;
DROP SERVER DB2SERVERLOCAL;
DROP WRAPPER DRDA;

-- Intentar crear el wrapper DRDA con el path completo
CREATE WRAPPER DRDA LIBRARY '/opt/ibm/db2/V11.5/lib64/libdb2drda.so';

-- Crear el servidor remoto
CREATE SERVER DB2SERVERLOCAL
  TYPE DB2/LUW
  VERSION '11.5'
  WRAPPER DRDA
  AUTHORIZATION "db2inst1"
  PASSWORD "db2inst1"
  OPTIONS (
    DBNAME 'SAMPLE',
    HOST 'db2_remote',
    PORT '50000',
    TCP_NODELAY 'Y'
  );

-- Crear el mapeo de usuario
CREATE USER MAPPING FOR DB2INST1
  SERVER DB2SERVERLOCAL
  OPTIONS (
    REMOTE_AUTHID 'db2inst1',
    REMOTE_PASSWORD 'db2inst1'
  );

-- Crear apodos (Nicknames) para el esquema DB2INST1 remoto
CREATE NICKNAME db2Ldept FOR DB2SERVERLOCAL.DB2INST1.DEPARTMENT;
CREATE NICKNAME db2Lemp FOR DB2SERVERLOCAL.DB2INST1.EMPLOYEE;
CREATE NICKNAME db2Lproj FOR DB2SERVERLOCAL.DB2INST1.PROJECT;

COMMIT;

-- Probar la conexión
SELECT TABNAME FROM SYSCAT.NICKTAB;
SELECT * FROM db2Ldept FETCH FIRST 5 ROWS ONLY;

TERMINATE;
