-- ============================================================================
-- init_federation.sql
-- ============================================================================

DROP NICKNAME db2Ldept;
DROP NICKNAME db2Lemp;
DROP NICKNAME db2Lproj;
DROP TABLE FILECLIENTES2; 
DROP USER MAPPING FOR DB2INST1 SERVER DB2SERVERLOCAL;
DROP SERVER DB2SERVERLOCAL;
DROP WRAPPER DRDA;

CREATE WRAPPER DRDA LIBRARY '/opt/ibm/db2/V11.5/lib64/libdb2drda.so';

CREATE SERVER DB2SERVERLOCAL
  TYPE DB2/LUW
  VERSION '11.5'
  WRAPPER DRDA
  AUTHORIZATION "db2inst1"
  PASSWORD "db2inst1"
  OPTIONS ( DBNAME 'SAMPLE', HOST 'db2_remote', PORT '50000' );

CREATE USER MAPPING FOR DB2INST1 SERVER DB2SERVERLOCAL
  OPTIONS ( REMOTE_AUTHID 'db2inst1', REMOTE_PASSWORD 'db2inst1' );

CREATE NICKNAME db2Ldept FOR DB2SERVERLOCAL.DB2INST1.DEPARTMENT;
CREATE NICKNAME db2Lemp   FOR DB2SERVERLOCAL.DB2INST1.EMPLOYEE;
CREATE NICKNAME db2Lproj  FOR DB2SERVERLOCAL.DB2INST1.PROJECT;

-- Definición como EXTERNAL TABLE (Tipo 'X')
-- Esto permite tratar el archivo CSV como una tabla de solo lectura 
-- que se integra en el catálogo de forma similar a un nodo federado.
CREATE EXTERNAL TABLE FILECLIENTES2 (
    CODCLI INTEGER NOT NULL,
    NAMECLI VARCHAR(100),
    DEUDACLI INTEGER
)
USING (
    DATAOBJECT '/tmp/file_clientes2.txt'
    DELIMITER ','
    REMOTESOURCE 'LOCAL'
);

COMMIT;
TERMINATE;
