-- connect to target
CONNECT TO BASETASD;

-- Create wrapper (use path if needed, but try default first)
CREATE WRAPPER DRDA;

-- Create server
CREATE SERVER DB2SERVERLOCAL
  TYPE DB2/LUW
  VERSION '11.5'
  WRAPPER DRDA
  AUTHORIZATION "db2inst1"
  PASSWORD "db2inst1"
  OPTIONS (
    DBNAME 'SAMPLE',
    HOST 'db2_remote',
    PORT '50000'
  );

-- User mapping
CREATE USER MAPPING FOR DB2INST1
  SERVER DB2SERVERLOCAL
  OPTIONS (
    REMOTE_AUTHID 'db2inst1',
    REMOTE_PASSWORD 'db2inst1'
  );

-- Nicknames
CREATE NICKNAME db2Ldept FOR DB2SERVERLOCAL.DB2INST1.DEPARTMENT;
CREATE NICKNAME db2Lemp FOR DB2SERVERLOCAL.DB2INST1.EMPLOYEE;
CREATE NICKNAME db2Lproj FOR DB2SERVERLOCAL.DB2INST1.PROJECT;

COMMIT;

-- Test
SELECT * FROM db2Ldept FETCH FIRST 5 ROWS ONLY;
